version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
